//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC2.LCCompiler.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LC2.LCCompiler.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The &quot;return&quot; statement must return an object of type castable to &quot;{0}&quot;.
        /// </summary>
        internal static string ErrorFunctionMustReturnCastable {
            get {
                return ResourceManager.GetString("ErrorFunctionMustReturnCastable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Function &quot;{0}&quot; does not return any value.
        /// </summary>
        internal static string ErrorFunctionReurnVoid {
            get {
                return ResourceManager.GetString("ErrorFunctionReurnVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Module &quot;{0}&quot; is not connected to this project.
        /// </summary>
        internal static string ErrorModuleNotFound {
            get {
                return ResourceManager.GetString("ErrorModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot use a module within itself.
        /// </summary>
        internal static string ErrorRecurrentUSE {
            get {
                return ResourceManager.GetString("ErrorRecurrentUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element &quot;{0}&quot; not found in current scope.
        /// </summary>
        internal static string ErrorSymbolNotFound {
            get {
                return ResourceManager.GetString("ErrorSymbolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modules &quot;{0}&quot; and &quot;{1}&quot; have the same public objects named &quot;{2}&quot;.
        /// </summary>
        internal static string ErrorUseModuleObjectConflict {
            get {
                return ResourceManager.GetString("ErrorUseModuleObjectConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Label &quot;{0}&quot; is not defined.
        /// </summary>
        internal static string LinkerErrorLabelNotDefined {
            get {
                return ResourceManager.GetString("LinkerErrorLabelNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object &quot;{0}&quot; overrides object in module &quot;{1}&quot;.
        /// </summary>
        internal static string WarningObjectOverridden {
            get {
                return ResourceManager.GetString("WarningObjectOverridden", resourceCulture);
            }
        }
    }
}
