; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "lccompiler"
#define MyAppVersion "0.1.1_alpha"
#define MyAppPublisher "DiMoon Electronics"
#define MyAppURL "https://lc2.dimoon.ru/"
#define MyAppExeName "bin/lccompiler.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{1C1ED74F-E046-4498-A513-33A80BDC404F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\DiMoonTools\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DefaultGroupName={#MyAppName}
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename={#MyAppName}_{#MyAppVersion}_setup
SolidCompression=yes
WizardStyle=modern
LicenseFile=..\LICENSE

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Files]
Source: "..\source\lcc\bin\Release\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\LICENSE"; DestDir: "{app}\"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKLM; Subkey: "Software\DiMoonTools"; Flags: uninsdeletekeyifempty
Root: HKLM; Subkey: "Software\DiMoonTools\lccompiler"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\DiMoonTools\lccompiler\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"

[Code]
#include "EnvPathUtils.pas"

function GetCompilerPath(): string;
begin
  Result := ExpandConstant('{app}\bin');
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then begin
    AddToPath(GetCompilerPath());
  end;
end;

procedure DeinitializeUninstall();
begin
  RemoveFromPath(GetCompilerPath());
end;
